baseURL = 'https://coinmore.io/'
languageCode = 'en-us'
[params]
  hugoVersion = "0.121.0"
  siteName = 'CoinMore'

defaultContentLanguage = 'en'
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/english"


  [languages.ru]
    languageName = "Russian"
    weight = 2
    contentDir = "content/russian"
