baseURL = 'https://coinmore.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'


defaultContentLanguage = 'en'
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/english"


  [languages.ru]
    languageName = "Русский"
    weight = 2
    contentDir = "content/russian"
