baseURL = 'https://coinmore.io/'
languageCode = 'en-us'
disableKinds = ["taxonomy", "taxonomyTerm"]
enableGitInfo = true

[params]
  hugoVersion = "0.129.0"
  siteName = 'CoinMore'

defaultContentLanguage = 'en'
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/english"


  [languages.ru]
    languageName = "Russian"
    weight = 2
    contentDir = "content/russian"
